### ISSUE TITLE
`List.concat_map` does not exist in OCaml 4.08

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/karamel#327]
Minor issue, but KaRaMeL won't build with OCaml 4.08 since `List.concat_map`, used in `AstToCFlat`, does not exist before OCaml 4.10.
```
+ ocamlfind ocamlc -c -g -annot -bin-annot -strict-sequence -w @1-2-3@8..12@14..21@23..29-30@31..38-39-40-41@43@57 -package ppx_deriving.std -package ppx_deriving_yojson -package zarith -package pprint -package unix -package menhirLib -package sedlex -package process -package fix -package wasm -package visitors.ppx -package visitors.runtime -I src -I krmllib -I lib -I parser -o src/AstToCFlat.cmo src/AstToCFlat.ml
File "src/AstToCFlat.ml", line 339, characters 4-19:
Error: Unbound value List.concat_map
Command exited with code 2.
make: *** [Makefile:25: minimal] Error 10
```
The README states that 4.08 should be supported, so either than can be bumped or `concat_map` can simply be defined.

**Comment by msprotz** [comment]
Thanks for the report, Guido
